---
# defaults file for generic_docker_systemd

enable_db: true
create_user_and_db: true
create_network: "{{ enable_db }}"
create_volume: true

docker_service_prefix: docker.
method: pull
service_pre_command: "/usr/bin/docker pull {{ docker_image }}"
docker_network_name: "{{ service_name }}"
service_db_name: "{{ service_name }}-db"
docker_service_volume_name: "{{ service_name }}"

docker_image:
docker_db_image: mariadb:10.3
docker_command: |
  /usr/bin/docker run --rm --name "{{ service_name }}" \
  -v docker_service_volume_name:/data \
  --network "{{ service_name }}" \
  "{{ docker_image }}"

## db

db_type: mariadb

docker_service_directory_db:

db_pass:
db_user_pass: "{{ db_pass }}"
db_config_port: 3306
db_name:
db_user:

db_setup_required: (db_type == 'mariadb' and not database_mariadb_conf.stat.exists ) or (db_type == 'postrgres' and not database_postgres_conf.stat.exists ) or (db_type == 'mongo' and not database_mongo_conf.stat.exists )
