---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/.yamllint
platforms:
  - name: stretch
    image: library/debian:stretch
provisioner:
  name: ansible
  options:
    become: true
    extra-vars:
      testing: true
      docker_registry_mirror: http://172.16.100.1:5000
      domain: anarres.local
  env:
    ANSIBLE_LIBRARY: /etc/ansible/library
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_whitelist: profile_tasks
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
