---
galaxy_info:
  author: m0wer
  description: >
    role to install and configure some basic utilities for a GNU/Linux server.

  license: GPLv3

  min_ansible_version: 2.4

  platforms:
    - name: Debian
      versions:
        - stretch

  galaxy_tags:
    docker
    ntp
    systemd
    anarres

dependencies: []
