---
# Defines tasks applicable for NTP (Network Time Protocol)

- name: Install ntp
  package:
    name: ntp
    state: present
  tags:
    - dependencies

- name: Configure ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - Restart ntp

- name: Ensure ntpd is running
  service:
    name: ntp
    state: started
    enabled: yes
